Merge in changes from the trunk. Add support for starting up the server from
Estimated hours taken: 20
Branches: deep2

Merge in changes from the trunk. Add support for starting up the server from
the CGI script. Start documentation.

diff --git a/tools/test_mercury b/tools/test_mercury
--- a/tools/test_mercury
+++ b/tools/test_mercury
@@ -11,7 +11,7 @@
 echo "test_mercury starting at `date`" 1>&2
 
 case $# in
-	4)	HOST=$1; ARCH=$2; FULLARCH=$3; C_COMPILER=$4 ;;
+	5)	HOST=$1; ARCH=$2; FULLARCH=$3; BRANCH=$4; C_COMPILER=$5 ;;
 	*)	echo "Usage: $0 host arch fullarch c_compiler" 1>&2; exit 1 ;;
 esac
 
@@ -42,37 +42,23 @@ umask 002
 
 #-----------------------------------------------------------------------------#
 
-DATE=`date '+%Y-%m-%d'`
-DAY=`date '+%e'`
-
-case $HOST in
-	murlibobo|taifun|hg|hydra)
-		#
-		# For these hosts:
-		# On odd-numbered days, test the release branch.
-		# On even-numbered days, test the main branch.
-		#
-		case $DAY in
-			*[13579]) INSTALL_DIR_NAME=mercury-0.10 ;;
-			*)	  INSTALL_DIR_NAME=mercury-latest ;;
-		esac
-		;;
-	*)
-		#
-		# For the remaining hosts, do the reverse:
-		# On odd-numbered days, test the main branch.
-		# On even-numbered days, test the release branch.
-		#
-		case $DAY in
-			*[13579]) INSTALL_DIR_NAME=mercury-latest ;;
-			*)	  INSTALL_DIR_NAME=mercury-0.10 ;;
-		esac
-		;;
-esac
-
 #
 # We set the following variables according to which
 # branch we're testing.
+#
+# BRANCH:
+# An abstract name for the branch, i.e. `0.10' or `latest'.
+# This is not the same as the branch name used by CVS.
+#
+# TEST_ID:
+# A name that identifies the version being tested.
+# This should include all the relevant test
+# parameters, e.g. BRANCH, HOST, C_COMPILER.
+#
+# INSTALL_DIR_NAME:
+# The name of the directory in which to install this branch.
+# (Not the full path, just the final directory name.)
+# More generally used for naming stuff related to this branch.
 #
 # CHECKOUT_OPTS:
 # Options to pass to cvs checkout.
@@ -94,19 +80,27 @@ esac
 # This should usually be the same as $RELEASE_VERSION,
 # but with `*' instead of $DATE.
 #
-case $INSTALL_DIR_NAME in
-	mercury-latest)
+INSTALL_DIR_NAME=mercury-$BRANCH
+DATE=`date '+%Y-%m-%d'`
+case $BRANCH in
+	latest)
 		CHECKOUT_OPTS=-A
 		BASE_TAG_NAME=rotd
 		RELEASE_VERSION=rotd-$DATE
 		RELEASE_VERSION_PATTERN=rotd-*
 		;;
-	mercury-0.10)
-		CHECKOUT_OPTS=-rversion-0_10_x
-		BASE_TAG_NAME=version-0_10_x
-		RELEASE_VERSION=0.10-beta-$DATE
-		RELEASE_VERSION_PATTERN=0.10-beta-*
+	0.10)
+		CHECKOUT_OPTS=-rversion-0_10_y
+		#CHECKOUT_OPTS=-rversion-0_10_2
+		BASE_TAG_NAME=version-0_10_y
+		RELEASE_VERSION=0.10.2-beta-$DATE
+		#RELEASE_VERSION=0.10.2
+		RELEASE_VERSION_PATTERN=0.10.1*
 		;;
+esac
+case "$C_COMPILER" in
+	gcc)	TEST_ID=$BRANCH.$HOST ;;
+	*)	TEST_ID=$BRANCH.$HOST."$C_COMPILER" ;;
 esac
 
 #-----------------------------------------------------------------------------#
@@ -120,10 +114,17 @@ case $HOST in
 	roy) 		OPTIMIZE=-O4 ;;	# hlc
 	hydra)		OPTIMIZE=-O2 ;;
 	ender)		OPTIMIZE=-O3 ;;
-	venus) 		case $C_COMPILER in
+	venus) 		case "$C_COMPILER" in
 				gcc)	OPTIMIZE=-O5 ;;
 				*)	OPTIMIZE=-O2 ;;
 			esac ;;
+
+			# XXX There are some performance problems
+			# with deforestation (module_qual__process_assert takes
+			# forever to compile with --intermodule-optimization
+			# and --deforestation), so disable it for now.
+	earth)		OPTIMIZE="-O5 --intermodule-optimization --no-deforestation" ;;
+	mars)		OPTIMIZE=-O5 ;;
 	kryten) 	OPTIMIZE=-O1 ;;	# currently not used
 	rimmer) 	OPTIMIZE=-O1 ;; # currently not used
 esac
@@ -149,7 +150,7 @@ TEST_CFLAGS=""
 TEST_MLFLAGS=""
 
 case $FULLARCH in
-	i?86-*-linux*)
+	i*86-*-linux*)
 		# On x86 Linux, we need to set the following flags to enable
 		# shared libraries (and we need to use shared libraries to
 		# avoid running out of disk space...)
@@ -168,12 +169,12 @@ TESTDIR=/home/mercury/public/test_mercury
 DIR=$TESTDIR/test_dirs/$HOST
 
 case $HOST in
-	hg|ender|roy|venus) 	
+	hg|ender|roy|venus|earth|mars) 	
 		INSTALL_DIR=/home/$HOST/public/$INSTALL_DIR_NAME/$FULLARCH ;;
 	*)		
 		INSTALL_DIR=/home/mercury/public/$INSTALL_DIR_NAME/$FULLARCH ;;
 esac
-case $C_COMPILER in
+case "$C_COMPILER" in
 	gcc)	;;
 	*)	INSTALL_DIR="$INSTALL_DIR-$C_COMPILER" ;;
 esac
@@ -191,13 +192,13 @@ case $ARCH in
 		# due to a bug in the DEC loader, INSTALL_DIR should be
 		# as short as possible, to avoid overflow of fixed length
 		# buffers for -rpath options. The above definition is too long.
-		case $INSTALL_DIR_NAME in
-		mercury-latest) INSTALL_DIR=/home/mercury/public/.a ;;
-		mercury-0.8)	INSTALL_DIR=/home/mercury/public/.b ;;
-		mercury-0.9)	INSTALL_DIR=/home/mercury/public/.c ;;
-		mercury-0.10)	INSTALL_DIR=/home/mercury/public/.d ;;
+		case $BRANCH in
+		latest) INSTALL_DIR=/home/mercury/public/.a ;;
+		0.8)	INSTALL_DIR=/home/mercury/public/.b ;;
+		0.9)	INSTALL_DIR=/home/mercury/public/.c ;;
+		0.10)	INSTALL_DIR=/home/mercury/public/.d ;;
 		*)
-			echo "unknown INSTALL_DIR_NAME \`$INSTALL_DIR_NAME'!"
+			echo "unknown BRANCH \`$BRANCH'!"
 			exit 1
 			;;
 		esac
@@ -219,12 +220,16 @@ case $HOST in
 	ender) 		PARALLEL= ;; 	# one CPU
 	roy) 		PARALLEL= ;; 	# one CPU
 	venus) 		PARALLEL= ;; 	# one CPU
+	earth) 		PARALLEL= ;; 	# one CPU
+	mars) 		PARALLEL= ;; 	# one CPU
 	*)		PARALLEL= ;;
 esac
 
 # version of the mercury compiler to use for bootstrapping
 case $HOST in
-	hg|ender|roy|venus)
+	hg|ender|roy|venus|earth)
+		# XXX Add mars to the list above once a compiler
+		# is installed there.
 		BOOTSTRAP_MERCURY_COMPILER=/home/$HOST/public/$INSTALL_DIR_NAME/$FULLARCH/lib/mercury/bin/$FULLARCH/mercury_compile
 		;;
 	*)
@@ -296,10 +301,44 @@ case $HOST in
 			--enable-new-mercuryfile-struct" ;;
 	roy)
 		CONFIG_OPTS=""
+		DEFAULT_GRADE="hlc.gc"
+		export DEFAULT_GRADE
 		INSTALL_GRADE="hlc.gc"
 		INSTALL_LIBGRADES="hl.gc \
 			hlc.gc.prof hlc.gc.memprof hlc.gc.tr hlc.par.gc \
 			hl.gc.prof  hl.gc.memprof  hl.gc.tr  hl.par.gc"
+		# Test the asm_fast.gc.tr.rt grade, but not on the 0.10 branch,
+		# since the asm_fast.gc.tr.rt grade is not yet implemented
+		# in the 0.10 branch.
+		case $BRANCH in
+			0.10)	;;
+			*)	INSTALL_LIBGRADES="$INSTALL_LIBGRADES \
+					asm_fast.gc.tr.rt" ;;
+		esac
+		;;
+	hg)
+		CONFIG_OPTS=""
+		case "$C_COMPILER" in asm)
+			INSTALL_GRADE="hlc.gc"
+			INSTALL_LIBGRADES="asm_fast.gc asm_fast \
+				asm_fast.gc.prof asm_fast.prof  \
+				asm_fast.gc.memprof asm_fast.gc.tr \
+				asm_fast.gc.tr.debug hlc.par.gc"
+			;;
+		esac
+		;;
+	venus)
+		CONFIG_OPTS=""
+		case "$C_COMPILER" in lcc)
+			# For grade none.gc.tr.debug, lcc 4.1 gets an
+			# internal error when compiling library/hash_table.c.
+			# So we need to disable that grade.
+			INSTALL_LIBGRADES="none  \
+				none.gc.prof none.prof none.gc.memprof \
+				none.gc.tr \
+				hlc.gc hlc.par.gc"
+			;;
+		esac
 		;;
 	*)	
 		CONFIG_OPTS="" ;;
@@ -328,7 +367,55 @@ cd $DIR || { false; exit 1; }
 rm -f mercury/extras/dynamic_linking/dl.m
 cvs checkout $CHECKOUT_OPTS mercury tests || { false; exit 1; }
 case $HOST in
-	murlibobo|kryten|taifun|quicksilver|hg|hydra|roy|venus)
+	hg)
+		# Check out the Mercury gcc back-end interface sources
+		[ -d mercury-cvs ] || mkdir mercury-cvs
+		(cd mercury-cvs && cvs checkout $CHECKOUT_OPTS gcc/mercury) ||
+			{ false; exit 1; }
+		# Check out the main gcc sources.
+		# See <http://gcc.gnu.org/cvs.html>.
+		#
+		# Once the gcc sources have been checked out here,
+		# the Mercury autoconfiguration script should find them
+		# automatically, so we don't need to bother explicitly
+		# passing `--enable-gcc-back-end' to configure.
+		#
+		# Note that the `cvs login' command, namely
+		# `cvs -d :pserver:anoncvs@gcc.gnu.org:/cvs/gcc login'
+		# must be done manually, since there is no easy way to pass
+		# the password (`anoncvs') from a script.
+		# Once it is done once, it will be saved in the user's
+		# ~/.cvspass file, so it doesn't need to be done again.
+		#
+		# XXX This is commented out for now, to save bandwidth,
+		#     since currently we're using a fixed snapshot
+		#     (`-r gcc_ss_20010129') anyway.
+		#     Eventually this should change to use
+		#     `-r gcc_latest_snapshot'.
+		###date
+		###cvs -d :pserver:anoncvs@gcc.gnu.org:/cvs/gcc -z 9 \
+		###	checkout -r gcc_ss_20010129 gcc || { false; exit 1; }
+		date
+		# Link the Mercury gcc back-end interface sources
+		# into the appropriate place in the gcc sources
+		(cd gcc/gcc && rm -f mercury && \
+			ln -s ../../mercury-cvs/gcc/mercury mercury) \
+			|| { false; exit 1; }
+		# Now configure and build the gcc directory.
+		# The gcc cvs repository includes some automatically
+		# generated files; we need to touch them here before
+		# running configure.
+		# XXX We should perhaps also do `make distclean' before
+		# configure.
+		(cd gcc && 
+			contrib/gcc_update --touch &&
+			sh configure --enable-languages=mercury &&
+			make) || status=1
+		date
+		;;
+esac
+case $HOST in
+	murlibobo|kryten|taifun|quicksilver|hg|hydra|roy|venus|ender|earth|mars)
 		[ -d mercury/extras/clpr/CVS ] ||
 		(cd mercury/extras && cvs checkout $CHECKOUT_OPTS clpr) ||
 			{ false; exit 1; }
@@ -368,18 +455,33 @@ cd mercury || { false; exit 1; }
 	esac
 # fi
 
+# We allow "asm" as a special value for the C_COMPILER
+# variable; it means to build with `--target asm'.
+# $CC holds the name of the real C compiler.
+
+case "$C_COMPILER" in
+	asm)
+		CC=gcc
+		target_opts="--target asm"
+		;;
+	*)
+		CC="$C_COMPILER"
+		target_opts=""
+		;;
+esac
+export CC
+
 autoconf || { false; exit 1; }
 rm -f config.cache
-CC=$C_COMPILER
-export CC
 ./configure --prefix=$INSTALL_DIR $CONFIG_OPTS || { false; exit 1; }
-mmake depend $PARALLEL || { false; exit 1; }
-mmake realclean MMAKEFLAGS=$PARALLEL || { false; exit 1; }
+mmake $target_opts depend $PARALLEL || { false; exit 1; }
+mmake $target_opts realclean MMAKEFLAGS=$PARALLEL || { false; exit 1; }
 ./configure --prefix=$INSTALL_DIR $CONFIG_OPTS || { false; exit 1; }
-mmake depend $PARALLEL || { false; exit 1; }
-version=`mmake version` || { false; exit 1; }
-fullarch=`mmake fullarch` || { false; exit 1; }
-tools/bootcheck -k -r -p -t $PARALLEL || $install_anyway || { false; exit 1; }
+mmake $target_opts depend $PARALLEL || { false; exit 1; }
+version=`mmake $target_opts version` || { false; exit 1; }
+fullarch=`mmake $target_opts fullarch` || { false; exit 1; }
+tools/bootcheck $target_opts -k -r -p -t $PARALLEL ||
+	$install_anyway || { false; exit 1; }
 cd .. || { false; exit 1; }
 
 #-----------------------------------------------------------------------------#
@@ -413,13 +515,17 @@ case $status in 0)
     # again, look back in the CVS archives for version 1.114 to see
     # the necessary code.
 
-    mmake install MMAKEFLAGS=$PARALLEL || status=1
+    # Note that we don't pass $target_opts when doing `mmake install_grades';
+    # that wouldn't work, since many of the grades can only be built with
+    # `--target c'.
+    mmake $target_opts install_main MMAKEFLAGS=$PARALLEL || status=1
+    mmake install_grades MMAKEFLAGS=$PARALLEL || status=1
     case "$INSTALL_GRADE" in
 	hl*)
 	    	# --split-c-files is not supported for the hl* grades
 	    	;;
-	*)	mmake install_split_library LIBGRADES= MMAKEFLAGS=$PARALLEL ||
-	    		status=1
+	*)	mmake install_split_library \
+			LIBGRADES= MMAKEFLAGS=$PARALLEL || status=1
 		;;
     esac
 
@@ -440,8 +546,13 @@ case $status in 0)
 
     [ -d $TESTDIR/logs ] || mkdir -p $TESTDIR/logs
     case $status in
-        0) date >> $TESTDIR/logs/install.$INSTALL_DIR_NAME.$HOST ;;
-        *) date >> $TESTDIR/logs/install-failed.$INSTALL_DIR_NAME.$HOST ;;
+        0) 
+	    date >> $TESTDIR/logs/install."$TEST_ID"
+	    rm -f $TESTDIR/logs/install-failed."$TEST_ID"
+	    ;;
+        *)
+	    date >> $TESTDIR/logs/install-failed."$TEST_ID"
+	    ;;
     esac
 esac
 
@@ -453,8 +564,8 @@ case $HOST in
 		# requires --enable-all-grades
 		GRADES="asm_fast.gc.tr asm_fast.tr"
 		;;
-	hg|quicksilver|hydra|ender|kryten|taifun|venus)
-		case $C_COMPILER in
+	hg|quicksilver|hydra|ender|kryten|taifun|venus|earth|mars)
+		case "$C_COMPILER" in
 			gcc)	GRADES="asm_fast.gc.tr" ;;
 			*)	GRADES="" ;;
 		esac
@@ -578,23 +689,42 @@ case $HOST in
 	hg)
 		GRADES="asm_fast.gc asm_fast
 			asm_fast.gc.prof asm_fast.prof
-			asm_fast.gc.memprof asm_fast.gc.tr asm_fast.gc.tr.debug
+			asm_fast.gc.memprof asm_fast.gc.tr
+			asm_fast.gc.tr.debug
 			asm_fast.par.gc hlc.gc"
 		;;
+
+	earth)	GRADES="asm_fast.gc asm_fast
+			asm_fast.gc.prof asm_fast.prof
+			asm_fast.gc.memprof asm_fast.gc.tr asm_fast.gc.tr.debug
+			hlc.gc hlc.par.gc"
+		;;
+
+	mars)	GRADES="asm_fast.gc asm_fast
+			asm_fast.gc.prof asm_fast.prof
+			asm_fast.gc.memprof asm_fast.gc.tr asm_fast.gc.tr.debug
+			hlc.gc hlc.par.gc"
+		;;
+
 	venus)
-		case $C_COMPILER in
+		case "$C_COMPILER" in
 			gcc)	GRADES="asm_fast.gc asm_fast
 				asm_fast.gc.prof asm_fast.prof
-				asm_fast.gc.memprof asm_fast.gc.tr asm_fast.gc.tr.debug
-				hlc.gc" ;;
-			*)	GRADES="none.gc none none.gc.prof
+				asm_fast.gc.memprof asm_fast.gc.tr
+				asm_fast.gc.tr.debug
+				hlc.gc hlc.par.gc" ;;
+			*)	# We don't test none.gc.tr.debug
+				# because it wasn't installed,
+				# due to lcc 4.1 internal error (see above)
+				GRADES="none.gc none none.gc.prof
 				none.prof none.gc.memprof none.gc.tr
-				none.gc.debug.tr.debug hlc.gc" ;;
+				hlc.gc hlc.par.gc" ;;
 		esac
 		;;
 	roy)
 		GRADES="hlc.gc hlc.gc.prof hlc.gc.memprof hlc.gc.tr hlc.par.gc
-			hl.gc  hl.gc.prof  hl.gc.memprof  hl.gc.tr  hl.par.gc"
+			hl.gc  hl.gc.prof  hl.gc.memprof  hl.gc.tr  hl.par.gc 
+			asm_fast.gc.tr.rt"
 		;;
 	ender)
 		GRADES="asm_fast.gc asm_fast
@@ -628,7 +758,8 @@ do
 		$PARALLEL || status=1
 	case $grade in
 		*.memprof*)
-			# we need to set LD_BIND_NOW=1 for profiling on DEC Alpha
+			# we need to set LD_BIND_NOW=1
+			# for profiling on DEC Alpha
 			(cd benchmarks &&
 			touch poly.m &&
 			mmake poly.depend &&
@@ -661,6 +792,16 @@ do
 			;;
 	esac
 done
+case $HOST in hg)
+	echo "test_mercury starting tests for --target asm at `date`" 1>&2
+	# XXX Note that some of these tests are currently expected to fail
+	# with `--target asm' (in particular the tests of tabling and
+	# nested modules), so we don't set status=1 if these tests fail.
+	./runtests --target asm -f "$TEST_MCFLAGS" -c "$TEST_CFLAGS" \
+		-g hlc.gc -m "$TEST_MGNUCFLAGS" -l "$TEST_MLFLAGS" \
+		$PARALLEL
+	;;
+esac
 cd ..
 
 #-----------------------------------------------------------------------------#
@@ -668,13 +809,17 @@ cd ..
 : update the unstable release
 
 case $HOST in murlibobo)
-	# XXX should remove old files
 	rsh $BETA_FTPHOST \
-		"echo rm -f $BETA_FTPDIR/mercury-*-$RELEASE_VERSION_PATTERN-unstable.tar.gz" &&
+		"rm -f $BETA_FTPDIR/mercury-compiler-$RELEASE_VERSION_PATTERN-unstable.tar.gz" &&
+	rsh $BETA_FTPHOST \
+		"rm -f $BETA_FTPDIR/mercury-extras-$RELEASE_VERSION_PATTERN-unstable.tar.gz" &&
+	rsh $BETA_FTPHOST \
+		"rm -f $BETA_FTPDIR/mercury-tests-$RELEASE_VERSION_PATTERN-unstable.tar.gz" &&
 	rcp $INSTALL_DIR_NAME-unstable/mercury-*-$version-unstable.tar.gz \
 		$BETA_FTPHOST:$BETA_FTPDIR 
-	# XXX should remove old files
-	echo rm -f $BETA_WEBDIR/mercury-*-$RELEASE_VERSION_PATTERN-unstable.tar.gz &&
+	rm -f $BETA_WEBDIR/mercury-compiler-$RELEASE_VERSION_PATTERN-unstable.tar.gz &&
+	rm -f $BETA_WEBDIR/mercury-extras-$RELEASE_VERSION_PATTERN-unstable.tar.gz &&
+	rm -f $BETA_WEBDIR/mercury-tests-$RELEASE_VERSION_PATTERN-unstable.tar.gz &&
 	cp $INSTALL_DIR_NAME-unstable/mercury-*-$version-unstable.tar.gz \
 		$BETA_WEBDIR
 	;;
@@ -693,6 +838,12 @@ case $HOST in
 		fullname=i686-pc-linux-libc2.1-gnu-O4
 		;;
 	venus)	
+		fullname=i686-pc-linux-libc2.1-gnu-O5
+		;;
+	earth)	
+		fullname=i686-pc-linux-libc2.1-gnu-O5-intermod
+		;;
+	mars)	
 		fullname=i686-pc-linux-libc2.1-gnu-O5
 		;;
 	roy)	
@@ -721,13 +872,13 @@ case $fullname in
 		;;
 esac
 
-case $C_COMPILER in
+case "$C_COMPILER" in
 	gcc)	;;
 	*)	fullname="$fullname-$C_COMPILER" ;;
 esac
 
-# cvs does not allow `.' in tag names, so we use `_' instead
-fullname_tag=`echo $fullname | tr . _`
+# cvs does not allow `.' or space in tag names, so we use `_' instead
+fullname_tag=`echo $fullname | tr ' .' __`
 
 {
 	cd $DIR/mercury &&
@@ -748,10 +899,10 @@ case $status in
     0) {
     	cd $DIR &&
 	{ [ -d $STABLE ] || mkdir $STABLE; } &&
-	rm -f $STABLE/mercury-*.$fullname.tar.gz &&
+	rm -f $STABLE/mercury-$RELEASE_VERSION_PATTERN.$fullname.tar.gz &&
 	$LN $UNSTABLE/mercury-$version.$fullname.tar.gz \
 		$STABLE/mercury-$version.$fullname.tar.gz &&
-	rsh $BETA_FTPHOST "rm -f $BETA_FTPDIR/mercury-*.$fullname.tar.gz" &&
+	rsh $BETA_FTPHOST "rm -f $BETA_FTPDIR/mercury-$RELEASE_VERSION_PATTERN.$fullname.tar.gz" &&
 	rcp $STABLE/mercury-$version.$fullname.tar.gz \
 		$BETA_FTPHOST:$BETA_FTPDIR &&
 	echo "test_mercury tagging stable $BASE_TAG_NAME, starting at `date`" 1>&2 &&
@@ -768,16 +919,12 @@ case $status in
     0)
 	: if we get this far, then it worked.
 	[ -d $TESTDIR/logs ] || mkdir -p $TESTDIR/logs
-	case $C_COMPILER in
-		gcc) date >> $TESTDIR/logs/successful_tests.$INSTALL_DIR_NAME.$HOST ;;
-		*) date >> $TESTDIR/logs/successful_tests.$INSTALL_DIR_NAME.$HOST."$C_COMPILER" ;;
-	esac
+	date >> $TESTDIR/logs/success."$TEST_ID"
 	case $HOST in murlibobo)
 	    cd $DIR &&
 		# Delete older stable versions that this one replaces
-		# XXX should remove old files
-	    echo rm -f $STABLE/mercury-*-$RELEASE_VERSION_PATTERN[0-9].tar.gz &&
-	    echo rm -f $STABLE/mercury-*-$version.tar.gz &&
+	    rm -f $STABLE/mercury-*-$RELEASE_VERSION_PATTERN[0-9].tar.gz &&
+	    rm -f $STABLE/mercury-*-$version.tar.gz &&
 	    $LN $UNSTABLE/mercury-compiler-$version-unstable.tar.gz \
 	        $STABLE/mercury-compiler-$version.tar.gz &&
 	    $LN $UNSTABLE/mercury-extras-$version-unstable.tar.gz \
@@ -785,10 +932,9 @@ case $status in
 	    $LN $UNSTABLE/mercury-tests-$version-unstable.tar.gz \
 	        $STABLE/mercury-tests-$version.tar.gz &&
 
-		# XXX should remove old files
 	    rsh $BETA_FTPHOST "\
-	    echo rm -f $BETA_FTPDIR/mercury-*-$RELEASE_VERSION_PATTERN[0-9].tar.gz && 
-	    echo rm -f $BETA_FTPDIR/mercury-*-$version.tar.gz && 
+	    rm -f $BETA_FTPDIR/mercury-*-$RELEASE_VERSION_PATTERN[0-9].tar.gz && 
+	    rm -f $BETA_FTPDIR/mercury-*-$version.tar.gz && 
 	    $LN $BETA_FTPDIR/mercury-compiler-$version-unstable.tar.gz \
 	        $BETA_FTPDIR/mercury-compiler-$version.tar.gz &&
 	    $LN $BETA_FTPDIR/mercury-extras-$version-unstable.tar.gz \
@@ -796,9 +942,9 @@ case $status in
 	    $LN $BETA_FTPDIR/mercury-tests-$version-unstable.tar.gz \
 	        $BETA_FTPDIR/mercury-tests-$version.tar.gz" &&
 
-		# XXX should remove old files
-	    echo rm -f $BETA_WEBDIR/mercury-*-$RELEASE_VERSION_PATTERN[0-9].tar.gz &&
-	    echo rm -f $BETA_WEBDIR/mercury-*-$version.tar.gz && 
+	    rm -f $BETA_WEBDIR/mercury-compiler-$RELEASE_VERSION_PATTERN[0-9].tar.gz &&
+	    rm -f $BETA_WEBDIR/mercury-extras-$RELEASE_VERSION_PATTERN[0-9].tar.gz &&
+	    rm -f $BETA_WEBDIR/mercury-tests-$RELEASE_VERSION_PATTERN[0-9].tar.gz &&
 	    $LN $BETA_WEBDIR/mercury-compiler-$version-unstable.tar.gz \
 	        $BETA_WEBDIR/mercury-compiler-$version.tar.gz &&
 	    $LN $BETA_WEBDIR/mercury-extras-$version-unstable.tar.gz \
